<a href="https://colab.research.google.com/github/sharadnatarajSJSU/CMPE-256-Spam-Filter/blob/main/CMPE_256_SPAM_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
import pandas as pd
import math

In [55]:
spam_dict = {'Free':0,'Click here':1,'visit':2,'open attachment':3,'call this number':4,'money':5,'out':6,'extra':7,'offer':8,'available':9,'pension':10,'opportunity':11,'chance':12,'investment':13}

In [56]:
print(spam_dict)

{'Free': 0, 'Click here': 1, 'visit': 2, 'open attachment': 3, 'call this number': 4, 'money': 5, 'out': 6, 'extra': 7, 'offer': 8, 'available': 9, 'pension': 10, 'opportunity': 11, 'chance': 12, 'investment': 13}


In [57]:
df1 = pd.read_csv('/content/Emails - Sheet1.csv')

In [58]:
df1.shape

(10, 3)

isolating the email messages.

In [59]:
docs=df1.iloc[:,2]

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
vectorizer = TfidfVectorizer(vocabulary=spam_dict)

In [64]:
X = vectorizer.fit_transform(docs)

In [65]:
print(X)

  (2, 10)	0.8944271909999159
  (2, 6)	0.4472135954999579
  (4, 12)	0.3779644730092272
  (4, 11)	0.3779644730092272
  (4, 7)	0.7559289460184544
  (4, 5)	0.3779644730092272
  (5, 13)	0.7071067811865475
  (5, 8)	0.7071067811865475


In [74]:
from scipy.sparse import csr_matrix
X=csr_matrix(X).toarray()
X

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4472136 , 0.        , 0.        , 0.        ,
        0.89442719, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.75592895, 0.        , 0.        ,
        0.        , 0.37796447, 0.37796447, 0.        ],
       [0.        , 0.        , 0. 

# We have now built the vector space model. The above matrix represents the TF-IDF for the vectors.

In [67]:
X = np.array(X)

In [75]:
types=df1.iloc[:,1]

In [76]:
y=[]

In [77]:
for i in types:
  if(i=='spam'):
    y.append(1)
  else:
    y.append(0)

In [78]:
y = np.array(y)

In [79]:
from sklearn.model_selection import train_test_split

In [81]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [72]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state=0)


In [83]:
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [84]:
y_pred=regressor.predict(x_test)

In [85]:
y_pred

array([1, 1])

In [86]:
y_test

array([1, 0])

#The model is trained. The accuracy is below normal. But can be improved with more data.

Let us use a new set of test data.

In [92]:
df_test = pd.read_csv('/content/Email Test - Sheet1 (1).csv')

In [93]:
df_test.shape

(4, 3)

In [95]:
X=df_test.iloc[:,2]

In [96]:
y=df_test.iloc[:,1]

In [110]:
vectorizer_new = TfidfVectorizer(vocabulary=spam_dict)

In [112]:
X_new = vectorizer_new.fit_transform(X)
X_new=csr_matrix(X_new).toarray()

In [113]:
X_new

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.37796447, 0.        , 0.        ,
        0.37796447, 0.        , 0.37796447, 0.        , 0.        ,
        0.37796447, 0.37796447, 0.37796447, 0.37796447],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [114]:
types = []

In [115]:
for i in y:
  if(i=='spam'):
    types.append(1)
  else:
    types.append(0)

In [116]:
y_new_pred = regressor.predict(X_new)

In [117]:
y_new_pred

array([1, 1, 1, 1])